platform:
 - x86
 - x64

environment:
  global:
    - ICU4C_URL=http://downloads.sourceforge.net/project/icu/ICU4C
  matrix:
    - ICU_MAJOR: 54
      ICU_MINOR: 1
      VS_TOOLSET: 10
      VS_VERSION: 2010
    - ICU_MAJOR: 54
      ICU_MINOR: 1
      VS_TOOLSET: 11
      VS_VERSION: 2012
    - ICU_MAJOR: 54
      ICU_MINOR: 1
      VS_TOOLSET: 12
      VS_VERSION: 2013

init:
  - SET VCVARSALL=C:\Program Files (x86)\Microsoft Visual Studio %VS_TOOLSET%.0\VC\vcvarsall.bat
  - SET PATH=C:\icu\bin;%PATH%

build_script:
  - cd C:\
  - IF %platform% == x86 CALL "%VCVARSALL%" x86
  - IF %platform% == x64 CALL "%VCVARSALL%" amd64
  - curl -L -O %ICU4C_URL%/%ICU_MAJOR%.%ICU_MINOR%/icu4c-%ICU_MAJOR%_%ICU_MINOR%-src.zip
  - 7z x icu4c-%ICU_MAJOR%_%ICU_MINOR%-src.zip
  - cd icu\source\allinone
  - IF %VS_VERSION% GTR 2010 devenv allinone /Upgrade
  - IF %platform% == x86 devenv allinone.sln /build "Win32|Release"
  - IF %platform% == x64 devenv allinone.sln /build "x64|Release"
  - icucheck %platform% Release
  - dir /s /b icu\bin
  - dir /s /b icu\lib

matrix:
  fast_finish: true
