platform:
 - x86
 - x64

environment:
  matrix:
    - icu_major: 54
      icu_minor: 1
      vs_toolset: 10
      vs_version: 2010
    - icu_major: 54
      icu_minor: 1
      vs_toolset: 11
      vs_version: 2012
    - icu_major: 54
      icu_minor: 1
      vs_toolset: 12
      vs_version: 2013

build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - SET PATH=C:\cygwin\bin;%PATH%
  - SET VCVARSALL=C:\Program Files (x86)\Microsoft Visual Studio %vs_toolset%.0\VC\vcvarsall.bat
  - IF %platform% == x86 CALL "%VCVARSALL%" x86
  - IF %platform% == x64 CALL "%VCVARSALL%" amd64
  - curl -L -O http://downloads.sourceforge.net/project/icu/ICU4C/%icu_major%.%icu_minor%/icu4c-%icu_major%_%icu_minor%-src.zip
  - 7z x icu4c-%icu_major%_%icu_minor%-src.zip
  - cd icu\source
  - dos2unix *
  - dos2unix -f configure
  - exec 0</dev/null; bash runConfigureICU Cygwin/MSVC -prefix=/cygdrive/c/icu/dist

matrix:
  fast_finish: true
