platform:
 - x86
 - x64

environment:
  global:
    ICU4C_URL: http://downloads.sourceforge.net/project/icu/ICU4C
    DATA_API_URL: http://apps.icu-project.org/datacustom/datacustom
  matrix:
    #- ICU_MAJOR: 54
    #  ICU_MINOR: 1
    #  VS_TOOLSET: 10
    #  VS_VERSION: 2010
    - ICU_MAJOR: 54
      ICU_MINOR: 1
      VS_TOOLSET: 11
      VS_VERSION: 2012
    #- ICU_MAJOR: 54
    #  ICU_MINOR: 1
    #  VS_TOOLSET: 12
    #  VS_VERSION: 2013

init:
  - SET PATH=C:\icu\bin;%PATH%
  - SET REQUEST_XML=%APPVEYOR_BUILD_FOLDER%/data_request_%ICU_MAJOR%.xml
  - IF %VS_VERSION% == 2010 CALL "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /%platform% /Release
  - IF %VS_VERSION% GTR 2010 IF %platform% == x86 CALL "C:\Program Files (x86)\Microsoft Visual Studio %VS_TOOLSET%.0\VC\vcvarsall.bat" x86
  - IF %VS_VERSION% GTR 2010 IF %platform% == x64 CALL "C:\Program Files (x86)\Microsoft Visual Studio %VS_TOOLSET%.0\VC\vcvarsall.bat" x86_amd64

build_script:
  # Download and extract.
  - cd C:\
  - curl -L -O %ICU4C_URL%/%ICU_MAJOR%.%ICU_MINOR%/icu4c-%ICU_MAJOR%_%ICU_MINOR%-src.zip
  - 7z x icu4c-%ICU_MAJOR%_%ICU_MINOR%-src.zip
  # Replace data with minimal data.
  - cd C:\icu\source\data\in
  - 'curl -o data_url.txt -X POST -d "@%REQUEST_XML%" --header "Content-Type: text/xml; charset=UTF-8" %DATA_API_URL%'
  - SET /p DATA_URL=<data_url.txt
  - curl -O %DATA_URL%
  - 7z x icudt%ICU_MAJOR%l.zip -aoa
  # Build and check.
  - cd C:\icu\source\allinone
  #- IF %VS_VERSION% == 2012 wdexpress allinone.sln /Upgrade
  - IF %VS_VERSION% GTR 2012 devenv allinone.sln /Upgrade
  - IF %VS_VERSION% == 2012 IF %platform% == x86 msbuild allinone.sln /p:Configuration="Release" /p:Platform="Win32" /p:VisualStudioVersion=11.0
  - IF %VS_VERSION% == 2012 IF %platform% == x64 msbuild allinone.sln /p:Configuration="Release" /p:Platform="x64" /p:VisualStudioVersion=11.0
  - IF %VS_VERSION% != 2012 %platform% == x86 msbuild allinone.sln /p:Configuration="Release" /p:Platform="Win32"
  - IF %VS_VERSION% != 2012 %platform% == x64 msbuild allinone.sln /p:Configuration="Release" /p:Platform="x64"
  #- icucheck %platform% Release
  # Create ZIP with icudtXX.dll, icuinXX.dll and icuucXX.dll
  - IF %platform% == x86 cd C:\icu\bin
  - IF %platform% == x64 cd C:\icu\bin64
  - 7z a %APPVEYOR_BUILD_FOLDER%\icu-win-%ICU_MAJOR%.%ICU_MINOR%-msvc%VS_VERSION%-%platform%.zip icudt%ICU_MAJOR%.dll icuin%ICU_MAJOR%.dll icuuc%ICU_MAJOR%.dll

artifacts:
  path: minimal-icu-$(ICU_MAJOR).$(ICU_MINOR)-msvc$(VS_VERSION)-$(platform).zip
  name: minimal-icu-$(ICU_MAJOR).$(ICU_MINOR)-msvc$(VS_VERSION)-$(platform)

deploy:
  release: minimal-icu-$(ICU_MAJOR).$(ICU_MINOR)
  description: 'Minimal ICU $(ICU_MAJOR).$(ICU_MINOR) DLLs'
  provider: GitHub
  auth_token:
    secure: JUtSd7iVOXwTUe295uQ0AL+qf3QVGwvz04eq4avhsLWorhdND+1tIXQuq99TnFd9
  artifact: minimal-icu-$(ICU_MAJOR).$(ICU_MINOR)-msvc$(VS_VERSION)-$(platform)
  prerelease: false

matrix:
  fast_finish: true
